---
- name: include distribution specific variables
  include: vars_loader.yml filename="{{ item }}"
  loop:
    - "{{ ansible_system }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution_release }}.yml"
