---
- name: include distribution specific variables
  include_vars:
    file: "{{ item }}"
  ignore_errors: true
  loop:
    - "{{ ansible_system }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution_release }}.yml"
